[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/phone"
  to = "tel:8632239932"
  status = 302

[[redirects]]
  from = "/call"
  to = "tel:8632239932"
  status = 302

[[redirects]]
  from = "/text"
  to = "sms:8632239932"
  status = 302

[[redirects]]
  from = "/sms"
  to = "sms:8632239932"
  status = 302

# 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# SEO-friendly redirects
[[redirects]]
  from = "/services"
  to = "/#services"
  status = 301

[[redirects]]
  from = "/about"
  to = "/#about"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/#contact"
  status = 301

[[redirects]]
  from = "/es"
  to = "/?lang=es"
  status = 301

[[redirects]]
  from = "/spanish"
  to = "/?lang=es"
  status = 301
